"""
Upload URL tests.

[P1-original] Local upload URL must have exactly one slash between host:port and path.
  Bug: uploads.py was concatenating str(request.base_url).rstrip("/") + "api/v1/..."
  which produced http://127.0.0.1:8013api/v1/... (no slash after port).

[P1-gateway] Local upload URL must NOT be under /api/v1/ (gateway-gated) — it must
  point at the public static /uploads/ mount so browsers can load images without
  the gateway auth token.

[P4] Upload URL is now a relative path (/uploads/<key>) when PUBLIC_UPLOAD_BASE_URL
  is not set, and an absolute URL when it is set.

[P3] Real Pillow-based image validation: a file that is truncated or corrupt must be
  rejected with 400 regardless of its declared Content-Type / magic bytes.
"""

from __future__ import annotations

import os
from io import BytesIO
from unittest.mock import patch

import pytest


# ---------------------------------------------------------------------------
# Helpers — real Pillow-decodable images
# ---------------------------------------------------------------------------

# Real 1×1 PNG generated by Pillow (passes verify() + load()).
_TINY_PNG = (
    b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01"
    b"\x08\x02\x00\x00\x00\x90wS\xde\x00\x00\x00\x0cIDATx\x9cc\xf8\xcf\xc0"
    b"\x00\x00\x03\x01\x01\x00\xc9\xfe\x92\xef\x00\x00\x00\x00IEND\xaeB`\x82"
)

# Real 1×1 JPEG generated by Pillow.
_TINY_JPEG = (
    b"\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00"
    b"\xff\xdb\x00C\x00\x08\x06\x06\x07\x06\x05\x08\x07\x07\x07\t\t\x08\n"
    b"\x0c\x14\r\x0c\x0b\x0b\x0c\x19\x12\x13\x0f\x14\x1d\x1a\x1f\x1e\x1d"
    b"\x1a\x1c\x1c $.\' \",#\x1c\x1c(7),01444\x1f\'9=82<.342\xff\xdb\x00C"
    b"\x01\t\t\t\x0c\x0b\x0c\x18\r\r\x182!\x1c!22222222222222222222222222"
    b"2222222222222222222222222222\xff\xc0\x00\x11\x08\x00\x01\x00\x01\x03"
    b"\x01\"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1f\x00\x00\x01\x05"
    b"\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03"
    b"\x04\x05\x06\x07\x08\t\n\x0b\xff\xc4\x00\xb5\x10\x00\x02\x01\x03\x03"
    b"\x02\x04\x03\x05\x05\x04\x04\x00\x00\x01}\x01\x02\x03\x00\x04\x11\x05"
    b"\x12!1A\x06\x13Qa\x07\"q\x142\x81\x91\xa1\x08#B\xb1\xc1\x15R\xd1\xf0"
    b"$3br\x82\t\n\x16\x17\x18\x19\x1a%&\'()*456789:CDEFGHIJSTUVWXYZcdefg"
    b"hijstuvwxyz\x83\x84\x85\x86\x87\x88\x89\x8a\x92\x93\x94\x95\x96\x97"
    b"\x98\x99\x9a\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xb2\xb3\xb4\xb5\xb6"
    b"\xb7\xb8\xb9\xba\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xd2\xd3\xd4\xd5"
    b"\xd6\xd7\xd8\xd9\xda\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xf1\xf2"
    b"\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xff\xc4\x00\x1f\x01\x00\x03\x01\x01"
    b"\x01\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04"
    b"\x05\x06\x07\x08\t\n\x0b\xff\xc4\x00\xb5\x11\x00\x02\x01\x02\x04\x04"
    b"\x03\x04\x07\x05\x04\x04\x00\x01\x02w\x00\x01\x02\x03\x11\x04\x05!1"
    b"\x06\x12AQ\x07aq\x13\"2\x81\x08\x14B\x91\xa1\xb1\xc1\t#3R\xf0\x15br"
    b"\xd1\n\x16$4\xe1%\xf1\x17\x18\x19\x1a&\'()*56789:CDEFGHIJSTUVWXYZcd"
    b"efghijstuvwxyz\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x92\x93\x94\x95"
    b"\x96\x97\x98\x99\x9a\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xb2\xb3\xb4"
    b"\xb5\xb6\xb7\xb8\xb9\xba\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xd2\xd3"
    b"\xd4\xd5\xd6\xd7\xd8\xd9\xda\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xf2"
    b"\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xff\xda\x00\x0c\x03\x01\x00\x02\x11"
    b"\x03\x11\x00?\x00\xd6\xa2\x8a+\xf3C\xf2\x03\xff\xd9"
)

# PNG magic header followed by garbage (truncated/corrupt — will fail Pillow decode).
_CORRUPT_PNG = b"\x89PNG\r\n\x1a\n" + b"\x00" * 20 + b"GARBAGE_NOT_VALID"

# Fake "image" that is actually Python source.
_FAKE_PY_AS_PNG = b"#!/usr/bin/env python3\nprint('hello')\n"


# ---------------------------------------------------------------------------
# Fixtures / helpers
# ---------------------------------------------------------------------------

def _do_upload(client, stored_key="menu-items/abc123.png", data=_TINY_PNG,
               content_type="image/png"):
    """POST to /admin/uploads/menu-image with save_image mocked."""
    with patch(
        "app.api.v1.endpoints.uploads.save_image",
        return_value=stored_key,
    ), patch(
        "app.api.v1.endpoints.uploads.storage_backend",
        return_value="local",
    ):
        resp = client.post(
            "/api/v1/admin/uploads/menu-image",
            files={"image": ("test.png", BytesIO(data), content_type)},
        )
    return resp


# ---------------------------------------------------------------------------
# [P4] URL shape: default relative path; absolute when PUBLIC_UPLOAD_BASE_URL set
# ---------------------------------------------------------------------------

class TestLocalUploadUrl:
    """Returned image_url must be a relative /uploads/ path by default."""

    def test_upload_url_is_relative_by_default(self, client):
        """Without PUBLIC_UPLOAD_BASE_URL, image_url is a relative path."""
        env = {k: v for k, v in os.environ.items() if k != "PUBLIC_UPLOAD_BASE_URL"}
        with patch.dict(os.environ, env, clear=True):
            resp = _do_upload(client)
        assert resp.status_code == 200, resp.text
        url = resp.json()["image_url"]
        assert url.startswith("/uploads/"), (
            f"Expected relative /uploads/ path, got: {url!r}"
        )
        assert "://" not in url, (
            f"Expected relative path (no scheme), got: {url!r}"
        )

    def test_upload_url_contains_stored_key(self, client):
        stored_key = "menu-items/deadbeef.png"
        env = {k: v for k, v in os.environ.items() if k != "PUBLIC_UPLOAD_BASE_URL"}
        with patch.dict(os.environ, env, clear=True):
            resp = _do_upload(client, stored_key=stored_key)
        assert resp.status_code == 200, resp.text
        url = resp.json()["image_url"]
        assert url.endswith(stored_key), (
            f"Expected URL to end with {stored_key!r} but got: {url!r}"
        )

    def test_upload_url_no_double_slash_in_path(self, client):
        env = {k: v for k, v in os.environ.items() if k != "PUBLIC_UPLOAD_BASE_URL"}
        with patch.dict(os.environ, env, clear=True):
            resp = _do_upload(client)
        assert resp.status_code == 200, resp.text
        url = resp.json()["image_url"]
        assert "//" not in url, (
            f"URL must not contain '//': {url!r}"
        )

    def test_upload_url_absolute_when_public_base_url_set(self, client):
        """When PUBLIC_UPLOAD_BASE_URL is set, image_url is an absolute URL."""
        with patch.dict(os.environ, {"PUBLIC_UPLOAD_BASE_URL": "https://cdn.example.com"}):
            resp = _do_upload(client)
        assert resp.status_code == 200, resp.text
        url = resp.json()["image_url"]
        assert url.startswith("https://cdn.example.com/uploads/"), (
            f"Expected absolute CDN URL, got: {url!r}"
        )

    def test_upload_url_public_base_url_trailing_slash_normalized(self, client):
        """PUBLIC_UPLOAD_BASE_URL with trailing slash must not produce double-slash."""
        with patch.dict(os.environ, {"PUBLIC_UPLOAD_BASE_URL": "https://cdn.example.com/"}):
            resp = _do_upload(client, stored_key="menu-items/img.png")
        assert resp.status_code == 200, resp.text
        url = resp.json()["image_url"]
        assert url == "https://cdn.example.com/uploads/menu-items/img.png", (
            f"Double-slash or wrong URL: {url!r}"
        )


# ---------------------------------------------------------------------------
# [P1-gateway] Public static URL tests (not under /api/v1/)
# ---------------------------------------------------------------------------

class TestLocalUploadUrlIsPublic:
    """Local upload URL must be on the public /uploads/ mount, not /api/v1/."""

    def test_upload_url_not_under_api_v1(self, client):
        """image_url must NOT contain /api/v1/ — that path requires gateway auth."""
        env = {k: v for k, v in os.environ.items() if k != "PUBLIC_UPLOAD_BASE_URL"}
        with patch.dict(os.environ, env, clear=True):
            resp = _do_upload(client)
        assert resp.status_code == 200, resp.text
        url = resp.json()["image_url"]
        assert "/api/v1/" not in url, (
            f"URL is under gateway-gated /api/v1/ path: {url!r}"
        )

    def test_upload_url_starts_with_uploads_prefix(self, client):
        """image_url path must start with /uploads/ (public static mount)."""
        env = {k: v for k, v in os.environ.items() if k != "PUBLIC_UPLOAD_BASE_URL"}
        with patch.dict(os.environ, env, clear=True):
            resp = _do_upload(client)
        assert resp.status_code == 200, resp.text
        url = resp.json()["image_url"]
        assert url.startswith("/uploads/"), (
            f"Expected path to start with '/uploads/' but got: {url!r}"
        )

    def test_maid_upload_url_starts_with_uploads_prefix(self, client):
        """Maid image upload also returns a /uploads/ URL (not /api/v1/)."""
        stored_key = "maids/cafebabe.jpg"
        env = {k: v for k, v in os.environ.items() if k != "PUBLIC_UPLOAD_BASE_URL"}
        with patch.dict(os.environ, env, clear=True):
            with patch(
                "app.api.v1.endpoints.uploads.save_image",
                return_value=stored_key,
            ), patch(
                "app.api.v1.endpoints.uploads.storage_backend",
                return_value="local",
            ):
                resp = client.post(
                    "/api/v1/admin/uploads/maid-image",
                    files={"image": ("test.jpg", BytesIO(_TINY_JPEG), "image/jpeg")},
                )
        assert resp.status_code == 200, resp.text
        url = resp.json()["image_url"]
        assert url.startswith("/uploads/"), (
            f"Maid image URL not public: {url!r}"
        )
        assert "/api/v1/" not in url, (
            f"Maid image URL is under gateway-gated /api/v1/: {url!r}"
        )


# ---------------------------------------------------------------------------
# [P3] Pillow full-decode validation
# ---------------------------------------------------------------------------

class TestImageByteValidation:
    """Upload must be rejected when Pillow cannot fully decode the image."""

    def test_real_png_bytes_accepted(self, client):
        """Genuine PNG (Pillow-generated) → 200."""
        resp = _do_upload(client, data=_TINY_PNG, content_type="image/png")
        assert resp.status_code == 200, resp.text

    def test_real_jpeg_bytes_accepted(self, client):
        """Genuine JPEG (Pillow-generated) → 200."""
        resp = _do_upload(client, data=_TINY_JPEG, content_type="image/jpeg")
        assert resp.status_code == 200, resp.text

    def test_non_image_bytes_declared_as_png_rejected_400(self, client):
        """Python source bytes declared as image/png must be rejected with 400."""
        with patch(
            "app.api.v1.endpoints.uploads.storage_backend",
            return_value="local",
        ):
            resp = client.post(
                "/api/v1/admin/uploads/menu-image",
                files={
                    "image": ("evil.py", BytesIO(_FAKE_PY_AS_PNG), "image/png")
                },
            )
        assert resp.status_code == 400, resp.text
        detail = resp.json()["detail"].lower()
        assert "image" in detail or "format" in detail, (
            f"Unexpected detail: {resp.json()['detail']!r}"
        )

    def test_text_file_declared_as_jpeg_rejected_400(self, client):
        """Plain text declared as image/jpeg → 400."""
        fake_text = b"Hello, I am not a JPEG.\n"
        with patch(
            "app.api.v1.endpoints.uploads.storage_backend",
            return_value="local",
        ):
            resp = client.post(
                "/api/v1/admin/uploads/menu-image",
                files={
                    "image": ("not_a_jpeg.jpg", BytesIO(fake_text), "image/jpeg")
                },
            )
        assert resp.status_code == 400, resp.text

    def test_corrupt_png_with_magic_header_rejected_400(self, client):
        """PNG magic header followed by garbage must be rejected with 400 by Pillow."""
        with patch(
            "app.api.v1.endpoints.uploads.storage_backend",
            return_value="local",
        ):
            resp = client.post(
                "/api/v1/admin/uploads/menu-image",
                files={
                    "image": ("corrupt.png", BytesIO(_CORRUPT_PNG), "image/png")
                },
            )
        assert resp.status_code == 400, resp.text
        detail = resp.json()["detail"].lower()
        assert "image" in detail or "format" in detail, (
            f"Unexpected detail: {resp.json()['detail']!r}"
        )

    def test_empty_file_rejected_400(self, client):
        """Empty payload → 400 (existing check, still passes)."""
        with patch(
            "app.api.v1.endpoints.uploads.storage_backend",
            return_value="local",
        ):
            resp = client.post(
                "/api/v1/admin/uploads/menu-image",
                files={
                    "image": ("empty.png", BytesIO(b""), "image/png")
                },
            )
        assert resp.status_code == 400, resp.text

    def test_unexpected_exception_propagates_not_swallowed_as_400(self):
        """An unexpected error in _validate_and_get_content_type must NOT be caught
        and converted to 400.  We verify this by calling the function directly and
        confirming the non-decode exception is NOT converted to HTTPException 400."""
        from fastapi import HTTPException
        from app.api.v1.endpoints.uploads import _validate_and_get_content_type
        from unittest.mock import patch as _patch

        # Patch PIL Image.open to raise an unexpected RuntimeError (not in _DECODE_ERRORS).
        with _patch("app.api.v1.endpoints.uploads.Image.open", side_effect=RuntimeError("unexpected internal error")):
            try:
                _validate_and_get_content_type(_TINY_PNG)
                assert False, "Expected an exception to be raised"
            except HTTPException as e:
                # If it's caught and re-raised as HTTPException 400, the narrow
                # except clause is still too broad — fail the test.
                assert False, (
                    f"RuntimeError was wrongly swallowed and turned into HTTPException {e.status_code}"
                )
            except RuntimeError:
                # Correct: RuntimeError propagates unmasked.
                pass
